services:
  xml-fixer-backend:
    build: ./xml-fixer-backend
    container_name: xml-fixer-backend
    ports:
      - "3000:3000"
    volumes:
      - ./xml-fixer-backend:/usr/app
    networks:
      - xml-fixer-network
    env_file:
      - ./xml-fixer-backend/.env

  xml-fixer-frontend:
    build: ./xml-fixer-frontend
    container_name: xml-fixer-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./xml-fixer-frontend:/usr/src/app
    networks:
      - xml-fixer-network

networks:
  xml-fixer-network:
    name: xml-fixer-network
    driver: bridge
